name: Test 🚀

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test 🚀
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: [ "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: requirements-dev.lock
          python-version: ${{ matrix.python }}

      - name: Install pip and wheel
        run: python -m pip install --upgrade pip wheel

      - name: Setup Rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Install deps
        run: rye sync

      - name: Run Pytest
        run: rye test
